admin_dashboard/urls.py
from django.urls import path

from . import views

app_name = "admin_dashboard"
urlpatterns = [
    path(
        "<int:user_id>/",
        views.admin_dashboard,
        name="dashboard",
    ),
    path(
        "<int:user_id>/students/",
        views.students,
        name="all",
    ),
    path(
        "<int:user_id>/students/enrolled",
        views.enrolled,
        name="enrolled",
    ),
    path(
        "<int:user_id>/students/unenrolled",
        views.unenrolled,
        name="unenrolled",
    ),
    path(
        "<int:user_id>/students/on_trial/",
        views.all_trials,
        name="all_trials",
    ),
    path(
        "<int:user_id>/students/active_trials/",
        views.active_trials,
        name="active_trials",
    ),
    path(
        "<int:user_id>/students/deactive_trials/",
        views.deactive_trials,
        name="deactive_trials",
    ),
    path(
        "<int:user_id>/students/send_meeting/<int:s_id>/<str:course_name>",
        views.send_meeting,
        name="send_meeting",
    ),
    path(
        "students/send_mail_to/<int:to>/",
        views.send_mail_to,
        name="send_mail_to",
    ),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"
urlpatterns = [
    path("<int:user_id>/", views.dashboard, name="dashboard"),
    path(
        "courses/",
        views.courses,
        name="courses",
    ),
    path("courses/<int:course_id>/", views.courses_data, name="courses_data"),
    path("take_trial/", views.take_trial, name="take_trial"),
    path("trial_confirm/<int:course_id>", views.confirm_trial, name="trial_confirm"),
    path("contact/", views.contact, name="contact"),
]

main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("courses/<int:course_id>", views.courses, name="courses"),
    path(
        "course/quran_with_tajweed/<int:course_id>",
        views.quran_with_tajweed,
        name="quran_with_tajweed",
    ),
    path(
        "course/islam_for_kids/<int:course_id>",
        views.islam_for_kids,
        name="islam_for_kids",
    ),
    path(
        "course/noorani_qauida/<int:course_id>",
        views.noorani_qauida,
        name="noorani_qauida",
    ),
    path("contact/", views.contact, name="contact"),
    path("test_error_404/", views.test_error_404, name="error_404"),
    path("test_error_403/", views.test_error_403, name="error_403"),
    path("test_error_400/", views.test_error_400, name="error_400"),
    path("test_error_500/", views.test_error_500, name="error_500"),
]

online_learning_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # APPLICATIONS URLS CONFIG. REF.
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/admin/", include("admin_dashboard.urls")),
    path("payments/", include("payments.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# error hanlders
handler404 = "main.views.error_404"
handler500 = "main.views.error_500"
handler403 = "main.views.error_403"
handler400 = "main.views.error_400"

admin_dashboard/models.py
from django.db import models

# Create your models here.

admin_dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.core.mail import send_mail
from online_learning_system.settings import EMAIL_HOST_USER

# Create your views here.
from main.models import (
    get_data_for_admin,
    get_students,
    Trial,
    get_user_enrollment_count,
)
from accounts.decorators import only_admin


@login_required
@only_admin
def admin_dashboard(request, user_id):
    context = get_data_for_admin()
    return render(request, "admin_dashboard/admin_dashboard.html", context=context)


@login_required
@only_admin
def students(request, user_id):
    students = User.objects.all().exclude(groups__id=4)
    enrollments_count = get_user_enrollment_count()
    students = zip(students, enrollments_count)
    context = {"students": students}
    return render(request, "admin_dashboard/all_students.html", context=context)


@login_required
@only_admin
def enrolled(request, user_id):
    students = get_students(_type="active")
    context = {
        "students": students,
    }
    return render(request, "admin_dashboard/enrolled.html", context=context)


@login_required
@only_admin
def unenrolled(request, user_id):
    students = get_students(_type="inactive")
    context = {
        "students": students,
    }
    return render(request, "admin_dashboard/unenrolled.html", context=context)


@login_required
@only_admin
def all_trials(request, user_id):
    trials = Trial.get_trials(Trial).exclude(status=True)
    context = {
        "trials": trials,
    }
    return render(request, "admin_dashboard/all_trials.html", context=context)


@login_required
@only_admin
def active_trials(request, user_id):
    trials = Trial.get_active_trialies(Trial).exclude(status=True)
    context = {
        "trials": trials,
    }
    return render(request, "admin_dashboard/active_trials.html", context=context)


@login_required
@only_admin
def deactive_trials(request, user_id):
    trials = Trial.get_inactive_trialies(Trial).exclude(status=True)
    context = {
        "trials": trials,
    }
    return render(request, "admin_dashboard/deactive_trials.html", context=context)


@login_required
@only_admin
def send_meeting(request, user_id, s_id, course_name):
    user = get_object_or_404(User, pk=s_id)
    if request.method == "POST":
        meeting_link = request.POST["meeting_link"]
        subject = "Al_Siraj Class Meeting"
        message = render_to_string(
            "admin_dashboard/meeting_email.html",
            {
                "meeting_id": meeting_link,
                "course": course_name,
                "admin": "Hafiz Nabeel",
            },
        )
        user.email_user(subject, message)
        messages.success(request, "Meeting has been sent Successfully")
        return redirect(request.build_absolute_uri())

    context = {
        "user": user,
    }
    return render(request, "admin_dashboard/send_meeting.html", context=context)


@login_required
@only_admin
def send_mail_to(request, to=0):
    if request.method == "POST":
        if to == 0:
            users = User.objects.filter(groups__name="students")
        elif to == 1:
            users = [enrollment.user for enrollment in get_students(_type="active")]
        elif to == 2:
            users = [enrollment.user for enrollment in get_students(_type="inactive")]
        elif to == 3:
            users = [trial.user for trial in Trial.get_trials(Trial)]
        else:
            raise Http404("Invalid Request")
        # sending Mails
        subject = request.POST["subject"]
        message = request.POST["message"]
        receivers = [user.email for user in users]
        status = send_mail(
            subject,
            message,
            from_email=EMAIL_HOST_USER,
            recipient_list=receivers,
        )
        if status != 0:
            messages.info(
                request, "Mails Has been successfully sent to the All Students."
            )
        else:
            messages.info(request, "Unable to send Mails.")
        return redirect("admin_dashboard:dashboard", user_id=request.user.id)
    else:
        context = {}
        return render(
            request, "admin_dashboard/send_mail_to_users.html", context=context
        )

admin_dashboard/templates/admin_dashboard/admin_dashboard.html
{% extends 'd_base.html' %}



{% block title %}
@{{request.user.username}} | Admin
{% endblock title %}


{% block dashboard_title %}
<div class="sidebar-brand-text mx-3">Admin panel</div>
{% endblock dashboard_title %}

{% block sidebar_items %}

<!-- Heading -->
<div class="sidebar-heading">
    Board
</div>

<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
        aria-controls="collapseTwo">
        <i class="fas fa-fw fa-university"></i>
        <span>Students</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Students</h6>
            <a class="collapse-item" href="{% url 'admin_dashboard:all' request.user.id %}">All Students</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:enrolled' request.user.id %}">Enrolled</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:unenrolled' request.user.id %}">UnEnrolled</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:all_trials' request.user.id %}">On Trial</a>
        </div>
    </div>
</li>

<!-- Nav Item - Utilities Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true"
        aria-controls="collapseUtilities">
        <i class="fas fa-fw fa-tag"></i>
        <span>Enrollments</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Enrollments</h6>
            <a class="collapse-item" href="{% url 'admin_dashboard:all' request.user.id %}">All Students</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:enrolled' request.user.id %}">Enrolled Students</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:unenrolled' request.user.id %}">UnEnrolled
                Students</a>
        </div>
    </div>
</li>

<!-- Nav Item - Utilities Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Trials" aria-expanded="true"
        aria-controls="collapseUtilities">
        <i class="fas fa-fw fa-book"></i>
        <span>Trials</span>
    </a>
    <div id="Trials" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Trials</h6>
            <a class="collapse-item" href="{% url 'admin_dashboard:all_trials' request.user.id %}">All Trials</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:active_trials' request.user.id %}">Active
                Students</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:deactive_trials' request.user.id %}">InActive
                Students</a>
        </div>
    </div>
</li>
<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
    Addons
</div>

<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false"
        aria-controls="collapsePages">
        <i class="fas fa-fw fa-folder"></i>
        <span>Quick Links</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Links</h6>
            <a class="collapse-item" href="{% url 'main:index' %}">Home</a>
            <a class="collapse-item" href="{% url 'main:about' %}">About</a>
            <a class="collapse-item" href="{% url 'dashboard:courses' %}">Courses</a>
            <a class="collapse-item" href="{% url 'main:contact' %}">Contact</a>
        </div>
    </div>
</li>

<!-- Nav Item - Change Password -->
<li class="nav-item">
    <a class="nav-link" href="{% url 'my_account' %}">
        <i class="fas fa-fw fa-user"></i>
        <span>Profile</span></a>
</li>

<!-- Nav Item - Logout -->
<li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">
        <i class="fas fa-sign-out-alt fa-sm fa-fw"></i>
        <span>Logout</span></a>
</li>

<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>
</ul>
{% endblock sidebar_items %}
<!-- End of Sidebar -->


{% block page_content %}
<!-- Displaying Messages -->
{% for message in messages %}
<div {% if message.tags == "warning"  %} class="alert alert-danger" {% else %} class="alert alert-{{ message.tags }}"
    {% endif %} role="alert">
    <strong>{% if message.tags == "warning"  %} Error {% else %} {{ message.tags }} {% endif %}</strong>
    <p>{{ message }}</p>
</div>
{% endfor %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4 mx-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    <a href="{% url 'admin:index' %}" class="d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm"><i
            class="fas fa-universal-access text-white-50 mr-2"></i>Admin Panel</a>
</div>
<div class="row">

    <!-- Students -->
    <div class="col-md-6">
        <div class="card shadow">
            <div class="card-header bg-info">
                <h6 class="m-0 font-weight-bold text-white">Students</h6>
            </div>
            <div class="card-body p-0">
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Total Students:
                        <span class="badge badge-info badge-pill">{{ students.students }}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Enrolled Students:
                        <span class="badge badge-info badge-pill">{{ students.enrolled }}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Trial Students:
                        <span class="badge badge-info badge-pill">{{ students.on_trial }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Enrollments -->
    <div class="col-md-6 mb-4">
        <div class="card shadow">
            <div class="card-header bg-success">
                <h6 class="font-weight-bold text-white">Enrollments</h6>
            </div>
            <div class="card-body p-0">
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Total Enrollments:
                        <span class="badge badge-success badge-pill">{{ enrollments.all }}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Active Enrollments:
                        <span class="badge badge-success badge-pill">{{ enrollments.active }}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Expired Enrollments:
                        <span class="badge badge-success badge-pill">{{ enrollments.inactive }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Actions -->
    <div class="col-md-6 mb-4">
        <div class="list-group">
            <a href="{% url 'admin_dashboard:send_mail_to' 0 %}" class="list-group-item list-group-item-action">
                Mail To All Students
            </a>
            <a href="{% url 'admin_dashboard:send_mail_to' 1 %}" class="list-group-item list-group-item-action">Mail To
                All Enrolled Students</a>
            <a href="{% url 'admin_dashboard:send_mail_to' 2 %}" class="list-group-item list-group-item-action">Mail To
                All UnEnrolled Students</a>
            <a href="{% url 'admin_dashboard:send_mail_to' 3 %}" class="list-group-item list-group-item-action">Mail To
                All Students On Trial</a>
        </div>
    </div>
</div>
{% endblock page_content %}

admin_dashboard/templates/admin_dashboard/enrolled.html
{% extends 'd_base.html' %}
{% load humanize %}


{% block title %}
@{{request.user.username}} | Enrolled
{% endblock title %}


{% block dashboard_title %}
<div class="sidebar-brand-text mx-3">Admin panel</div>
{% endblock dashboard_title %}


{% block sidebar_items %}

<!-- Heading -->
<div class="sidebar-heading">
    Board
</div>

<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
        aria-controls="collapseTwo">
        <i class="fas fa-fw fa-university"></i>
        <span>Students</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Students</h6>
            <a class="collapse-item" href="{% url 'admin_dashboard:all' request.user.id %}">All Students</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:enrolled' request.user.id %}">Enrolled</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:unenrolled' request.user.id %}">UnEnrolled</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:all_trials' request.user.id %}">On Trial</a>
        </div>
    </div>
</li>

<!-- Nav Item - Utilities Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true"
        aria-controls="collapseUtilities">
        <i class="fas fa-fw fa-tag"></i>
        <span>Enrollments</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Enrollments</h6>
            <a class="collapse-item" href="{% url 'admin_dashboard:all' request.user.id %}">All Students</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:enrolled' request.user.id %}">Enrolled Students</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:unenrolled' request.user.id %}">UnEnrolled
                Students</a>
        </div>
    </div>
</li>

<!-- Nav Item - Utilities Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Trials" aria-expanded="true"
        aria-controls="collapseUtilities">
        <i class="fas fa-fw fa-tag"></i>
        <span>Trials</span>
    </a>
    <div id="Trials" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Trials</h6>
            <a class="collapse-item" href="{% url 'admin_dashboard:all_trials' request.user.id %}">All Trials</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:active_trials' request.user.id %}">Active
                Students</a>
            <a class="collapse-item" href="{% url 'admin_dashboard:deactive_trials' request.user.id %}">InActive
                Students</a>
        </div>
    </div>
</li>
<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
    Addons
</div>

<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false"
        aria-controls="collapsePages">
        <i class="fas fa-fw fa-folder"></i>
        <span>Quick Links</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Links</h6>
            <a class="collapse-item" href="{% url 'main:index' %}">Home</a>
            <a class="collapse-item" href="{% url 'main:about' %}">About</a>
            <a class="collapse-item" href="{% url 'dashboard:courses' %}">Courses</a>
            <a class="collapse-item" href="{% url 'main:contact' %}">Contact</a>
        </div>
    </div>
</li>

<!-- Nav Item - Change Password -->
<li class="nav-item">
    <a class="nav-link" href="{% url 'my_account' %}">
        <i class="fas fa-fw fa-user"></i>
        <span>Profile</span></a>
</li>

<!-- Nav Item - Logout -->
<li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">
        <i class="fas fa-sign-out-alt fa-sm fa-fw"></i>
        <span>Logout</span></a>
</li>

<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>

</ul>
{% endblock sidebar_items %}
<!-- End of Sidebar -->


{% block page_content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4 mx-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    <a href="{% url 'admin:index' %}" class="d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm"><i
            class="fas fa-universal-access text-white-50 mr-2"></i>Admin Panel</a>
</div>

<div class="row">
    <div class="col-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Students</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                        aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Actions On Students:</div>
                        <a class="dropdown-item" href="#">Deactivate unEnrolled Students</a>
                        <a class="dropdown-item" href="#">Deactivate completed Trials</a>
                        <a class="dropdown-item" href="#">Email Enrolled Students</a>
                        <a class="dropdown-item" href="#">Email UnEnrolled Students</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body table-bordered table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>UserName</th>
                            <th>Course</th>
                            <th>Enrollment Date</th>
                            <th>Enrollment expiery Date</th>
                            <th>Enrollment Status</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for student in students %}
                        <tr>
                            <td scope="row">{{ student.user.username }}</td>
                            <td>{{ student.course }}</td>
                            <td>{{ student.timestamp|naturaltime }}</td>
                            <td>{{ student.expiries_at|naturaltime }}</td>
                            <td>{% if student.enrollment_status %}
                                <span class="text-success">Active</span>
                                {% else %}
                                <span class="text-danger">Expired</span>
                                {% endif %}
                            </td>
                            <td><a
                                    href="{% url 'admin_dashboard:send_meeting' request.user.id student.user.id student.course %}">Send
                                    Meeting</a></td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock page_content %}

admin_dashboard/templates/admin_dashboard/meeting_email.html
{% autoescape off %}
Email From Al-Siraj,
===================================================

Assalam-O-Alaikum,
You Are Enrolled At Course: {{course}}
here is your skype meeting link: {{ meeting_link }}
please join meeting at correct time to take your class.

Regards: {{ admin }}
===================================================
{% endautoescape %}