dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"
urlpatterns = [
    path("<int:user_id>/", views.dashboard, name="dashboard"),
    path(
        "courses/",
        views.courses,
        name="courses",
    ),
    path("courses/<int:course_id>/", views.courses_data, name="courses_data"),
    path("take_trial/", views.take_trial, name="take_trial"),
    path("trial_confirm/<int:course_id>", views.confirm_trial, name="trial_confirm"),
    path("contact/", views.contact, name="contact"),
]

main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("courses/<int:course_id>", views.courses, name="courses"),
    path(
        "course/quran_with_tajweed/<int:course_id>",
        views.quran_with_tajweed,
        name="quran_with_tajweed",
    ),
    path(
        "course/islam_for_kids/<int:course_id>",
        views.islam_for_kids,
        name="islam_for_kids",
    ),
    path(
        "course/noorani_qauida/<int:course_id>",
        views.noorani_qauida,
        name="noorani_qauida",
    ),
    path("contact/", views.contact, name="contact"),
    path("test_error_404/", views.test_error_404, name="error_404"),
    path("test_error_403/", views.test_error_403, name="error_403"),
    path("test_error_400/", views.test_error_400, name="error_400"),
    path("test_error_500/", views.test_error_500, name="error_500"),
]

online_learning_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # APPLICATIONS URLS CONFIG. REF.
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/admin/", include("admin_dashboard.urls")),
    path("payments/", include("payments.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# error hanlders
handler404 = "main.views.error_404"
handler500 = "main.views.error_500"
handler403 = "main.views.error_403"
handler400 = "main.views.error_400"

payments/urls.py
from django.urls import path

from . import views

app_name = "payments"
urlpatterns = [
    path("checkout/<int:course_id>", views.checkout, name="checkout"),
    path(
        "checkout/<int:course_id>/redirect/<str:T_method>/",
        views.checkout_redirect,
        name="checkout_redirect",
    ),
    path(
        "api/test_checkout/<int:course_id>",
        views.test_checkout,
        name="checkout_testing",
    ),
    path(
        "api/test_checkout/confirmation",
        views.test_checkout_confirmation,
        name="checkout_testing",
    ),
    path(
        "payment_confirm/<int:course_id>/<int:user_id>",
        views.payment_confirm,
        name="payment_confirm",
    ),
    path(
        "payment/status/<int:enrollment_id>/<int:transaction_id>",
        views.payment_status,
        name="payment_status",
    ),
    path(
        "payment/message/",
        views.payment_message,
        name="payment_message",
    ),
]

payments/models.py
from django.db import models
from django.shortcuts import Http404

from main.models import Enrollment

# Create your models here.


class Transaction(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=70)
    transaction_retreival_reference_no = models.CharField(max_length=200, null=True)
    total_amount = models.IntegerField()
    paid_amount = models.IntegerField()
    status = models.BooleanField(default=False)
    enrollment = models.OneToOneField(Enrollment, on_delete=models.CASCADE, null=True)

    def get_transaction(self, transaction_id, enrollment_id):
        transaction = self.objects.filter(
            id=transaction_id, enrollment__id=enrollment_id
        )
        if transaction:
            return transaction[0]
        else:
            raise Http404("Page Not Found")

payments/views.py
from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.contrib.auth.models import User
from django.template.loader import render_to_string

from .models import Transaction
from accounts.decorators import allowed_users, only_admin
from main.models import Course, Enrollment
from main.models import add_user_to_group, remove_user_from_group
from .transaction import (
    PostData,
    validate_data,
    extract_transaction_data,
    create_transaction,
    check_payment_status,
)


# Create your views here.


@login_required
@allowed_users(allowed_roles=["students"])
def checkout(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    if request.method == "POST":
        payment_method = request.POST["Payment_method"]
        return redirect(
            "payments:checkout_redirect", course_id=course_id, T_method=payment_method
        )
    context = {"course": course}
    return render(request, "payments/checkout.html", context=context)


@login_required
@allowed_users(allowed_roles=["students"])
def checkout_redirect(request, course_id, T_method):
    course = get_object_or_404(Course, pk=course_id)
    if course is not None:
        jazzcash_post_data = PostData(course, request.user, T_method)
        jazzcash_post_data.set_return_url(course, request.user)
    context = {
        "post_data": jazzcash_post_data.data,
        "post_url": jazzcash_post_data.JAZZCASH_HTTP_POST_URL,
    }
    return render(request, "payments/checkout_redirect.html", context=context)


@csrf_exempt
@allowed_users(allowed_roles=["students"])
def payment_confirm(request, course_id, user_id):
    # Getting the user and course data
    course = get_object_or_404(Course, pk=course_id)
    user = get_object_or_404(User, pk=user_id)
    if request.method == "POST":
        # fetching data if request method is POST
        data = extract_transaction_data(request)
        if validate_data(data, course.to_PKR()) and check_payment_status(
            data["ResponseCode"]
        ):
            # Store Enrollment and Transaction For User If
            # Data is valid
            enrollment = Enrollment.objects.create(user=user, course=course)
            transaction = create_transaction(data, enrollment)
            # redirecting the user the Payment Status Page
            return redirect(
                "payments:payment_status",
                enrollment_id=enrollment.id,
                transaction_id=transaction.id,
            )
        else:
            # Sending Warning Messages to the View if data is invalid
            messages.warning(
                request,
                "Some Serious error occurs please check transaction logs for more detail. Response Message: {} Response Code: {}".format(
                    data["ResponseMessage"], data["ResponseCode"]
                ),
            )
            return redirect("payments:payment_message")
    else:
        raise PermissionDenied("invalid request....")


def payment_message(request):
    return render(request, "payments/payment_confirm.html", context={})


@login_required
@allowed_users(allowed_roles=["students"])
def payment_status(request, enrollment_id, transaction_id):
    enrollment = Enrollment.get_enrollment(
        Enrollment, user_id=request.user.id, enrollment_id=enrollment_id
    )
    transaction = Transaction.get_transaction(
        Transaction, transaction_id=transaction_id, enrollment_id=enrollment.id
    )
    if transaction.status:
        enrollment.active = True
        enrollment.save()
        # sending course enrollment confirmation message to the user
        message = render_to_string(
            "payments/payment_email.html",
            {
                "enrollment": enrollment,
                "transaction": transaction,
            },
        )
        request.user.email_user("AL-Siraj Course Confirmation", message)
        # adding user to the enrolled_student group
        add_user_to_group(group_id=2, user_id=request.user.id)

        context = {"transaction": transaction}
        return render(request, "payments/payment_status.html", context=context)
    else:
        enrollment.delete()
        transaction.delete()
        messages.warning(request, "Payment Failed")
        return render(request, "payments/payment_status.html", {})
    raise Http404("Invalid Request")


# JAZZCASH PAGE REDIRECTION TEST PAGE VIEW
@login_required
@only_admin
def test_checkout(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    if course is not None:
        jazzcash_post_data = PostData(course, request.user)
    context = {
        "post_data": jazzcash_post_data.data,
        "post_url": jazzcash_post_data.JAZZCASH_HTTP_POST_URL,
    }
    return render(request, "payments/test_checkout.html", context=context)


# JAZZCASH PAGE REDIRECTION TEST PAGE VIEW
@login_required
@only_admin
def test_checkout_confirmation(request):
    return render(request, "payments/test_confirmation.html", context={})

payments/templates/payments/checkout.html
{% extends 'd_base.html' %}
{% load static %}


{% block title %}
@{{request.user.username}} | Courses
{% endblock title %}



{% block page_content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <div class="col-3 col-md-4 col-lg-3 col-xl-2">
                        <img src="{% static 'images/jazzcash-r45.png' %}" width="100%" height="100%" alt="">
                    </div>
                    <div class="col-9 col-md-8 col-lg-9 col-xl-10 p-4">
                        <h3 class="m-0 h3 font-weight-bold text-primary">Pay With Jazzcash</h6>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="data">
                        <h5 class="text-capitalize h5">Name: <span>{{ course.course_name }}</span></h5>
                        <h5 class="text-capitalize h5">Price: <span>{{ course.currency }}
                                {{ course.pricing }} | {{ course.to_PKR }} PKR</span></h5>

                    </div>
                    <div class="bg-light mt-3 p-3 rounded">
                        <span class="text-danger">NOTE:</span>
                        <p>JazzCash Mobile Account can be registered on any Jazz or Warid number. <br>
                            Biometric-verified Jazz and Warid customers can self-register their Mobile Account simply by
                            dialing *786#.
                        </p>
                    </div>

                    <form class="form-inline mt-3" method="POST">
                        {% csrf_token %}
                        <h6 class=" h6 mt-2">Select Payment Method:</h6>
                        <div class="form-check ml-0 ml-sm-4">
                            <input class="form-check-input" type="radio" name="Payment_method" id="CardPayment"
                                value="MPAY" checked>
                            <label class="form-check-label" for="CardPayment">
                                <img src="{% static 'images/visa-master-card.png' %}" width="100px"
                                    alt="Via Visa Or Master Card">
                            </label>
                        </div>
                        <div class="form-check ml-0 ml-sm-4">
                            <input class="form-check-input" type="radio" name="Payment_method" id="MobilePayment"
                                value="MWALLET">
                            <label class="form-check-label" for="MobilePayment">
                                <img src="{% static 'images/jazzcash-logo.png' %}" width="100px"
                                    alt="JazzCash Mobile Account">
                            </label>
                        </div>
                        <a href="#!" class="btn btn-secondary ml-auto">Back</a>
                        <button class="btn btn-success ml-2">Pay</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock page_content %}

payments/templates/payments/payment_confirm.html
{% extends 'd_base.html' %}
{% load static %}


{% block title %}
@{{request.user.username}} | Courses
{% endblock title %}


{% block stylesheet %}
<style>
    .jsformWrapper {
        border: 1px solid rgba(196, 21, 28, 0.50);
        padding: 2rem;
        width: 100%;
        margin: 0 auto;
        border-radius: 2px;
        margin-top: 2rem;
        box-shadow: 0 7px 5px #eee;
    }

    @keyframes spinner-border {
        to {
            transform: rotate(360deg);
        }
    }

    .spinner-border {
        display: inline-block;
        width: 2rem;
        height: 2rem;
        vertical-align: text-bottom;
        border: .25em solid currentColor;
        border-right-color: transparent;
        border-radius: 50%;
        -webkit-animation: spinner-border .75s linear infinite;
        animation: spinner-border .75s linear infinite;
    }

    .spinner-border-sm {
        height: 1rem;
        border-width: .2em;
    }
</style>
{% endblock stylesheet %}


{% block sidebar_items %}

<!-- Heading -->
<div class="sidebar-heading">
    Board
</div>

<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
        aria-controls="collapseTwo">
        <i class="fas fa-fw fa-university"></i>
        <span>Admission</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Cousrses</h6>
            <a class="collapse-item" href="{% url 'dashboard:courses_data' 1 %}">quran with tajweed</a>
            <a class="collapse-item" href="{% url 'dashboard:courses_data' 2 %}">islam for kids</a>
            <a class="collapse-item" href="{% url 'dashboard:courses_data' 3 %}">noorani qauida</a>
        </div>
    </div>
</li>

<!-- Nav Item - Utilities Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true"
        aria-controls="collapseUtilities">
        <i class="fas fa-fw fa-tag"></i>
        <span>Take Trial</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Courses</h6>
            <a class="collapse-item" href="">quran with tajweed</a>
            <a class="collapse-item" href="">islam for kids</a>
            <a class="collapse-item" href="">noorani qauida</a>
        </div>
    </div>
</li>

<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
    Addons
</div>

<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false"
        aria-controls="collapsePages">
        <i class="fas fa-fw fa-folder"></i>
        <span>Quick Links</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Links</h6>
            <a class="collapse-item" href="{% url 'main:index' %}">Home</a>
            <a class="collapse-item" href="{% url 'main:about' %}">About</a>
            <a class="collapse-item" href="{% url 'dashboard:courses' %}">Courses</a>
            <a class="collapse-item" href="{% url 'main:contact' %}">Contact</a>
        </div>
    </div>
</li>

<!-- Nav Item - Change Password -->
<li class="nav-item">
    <a class="nav-link" href="{% url 'my_account' %}">
        <i class="fas fa-fw fa-user"></i>
        <span>Profile</span></a>
</li>

<!-- Nav Item - Logout -->
<li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">
        <i class="fas fa-sign-out-alt fa-sm fa-fw"></i>
        <span>Logout</span></a>
</li>

<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>

</ul>
{% endblock sidebar_items %}

{% block page_content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3">
                    <h3 class="h3 text-danger">Payment Failed!</h3>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    {% for message in messages %}
                    <div {% if message.tags == "warning"  %} class="alert alert-danger" {% else %}
                        class="alert alert-{{ message.tags }}" {% endif %} role="alert">
                        <strong>{% if message.tags == "warning"  %} Error {% else %} {{ message.tags }}
                            {% endif %}</strong>
                        <p>{{ message }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock page_content %}

payments/templates/payments/payment_email.html
{% autoescape off %}
Assalam-o-Alaikum,
===================================================
You have sucessfuly enrolled the course: {{ enrollment.course }}
please go to dashboard and request the admin for a meeting to discuss the time table. our servies are availble to you 24
hours.
Thanks For Al-Siraj

Transaction Details:
Reference Number: {{ transaction.transaction_retreival_reference_no }}</>
Transaction ID: {{ transaction.transaction_id }} </pre>
Total Amount: {{ transaction.total_amount }} PKR</pre>
Paid Amount: {{ transaction.paid_amount }} PKR</pre>
Payment Status: Success

===================================================
{% endautoescape %}

payments/templates/payments/payment_status.html
{% extends 'd_base.html' %}
{% load static %}


{% block title %}
@{{request.user.username}} | Courses
{% endblock title %}


{% block stylesheet %}
<style>
    .jsformWrapper {
        border: 1px solid rgba(196, 21, 28, 0.50);
        padding: 2rem;
        width: 100%;
        margin: 0 auto;
        border-radius: 2px;
        margin-top: 2rem;
        box-shadow: 0 7px 5px #eee;
    }

    @keyframes spinner-border {
        to {
            transform: rotate(360deg);
        }
    }

    .spinner-border {
        display: inline-block;
        width: 2rem;
        height: 2rem;
        vertical-align: text-bottom;
        border: .25em solid currentColor;
        border-right-color: transparent;
        border-radius: 50%;
        -webkit-animation: spinner-border .75s linear infinite;
        animation: spinner-border .75s linear infinite;
    }

    .spinner-border-sm {
        height: 1rem;
        border-width: .2em;
    }
</style>
{% endblock stylesheet %}

{% block page_content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3">
                    {% if transaction.status %}
                    <!-- Payment successful -->
                    <h3 class="text-success h3">Your Payment has been Successful</h3>
                    {% else %}
                    <h3 class="text-danger h3">Your Payment has Failed</h3>
                    {% endif %}

                </div>
                <!-- Card Body -->
                <div class="card-body">
                    {% if transaction.status %}
                    <!-- Payment successful -->
                    <h5 class="h5 text-secondary mb-3">Payment Information</h5>
                    <pre><b>Reference Number:</b>        {{ transaction.transaction_retreival_reference_no }}</pre>
                    <pre><b>Transaction ID:</b>          {{ transaction.transaction_id }} </pre>
                    <pre><b>Total Amount:</b>            {{ transaction.total_amount }} PKR</pre>
                    <pre><b>Paid Amount:</b>             {{ transaction.paid_amount }} PKR</pre>
                    <pre><b>Payment Status:</b>          Success</pre>
                    {% else %}
                    <!-- displaying the non form field errors -->
                    {% for message in messages %}
                    <div {% if message.tags == "warning"  %} class="alert alert-danger" {% else %}
                        class="alert alert-{{ message.tags }}" {% endif %} role="alert">
                        <strong>{% if message.tags == "warning"  %} Error {% else %} {{ message.tags }}
                            {% endif %}</strong>
                        <p>{{ message }}</p>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock page_content %}

payments/templates/payments/test_confirmation.html
{% extends 'd_base.html' %}
{% load static %}


{% block title %}
@{{request.user.username}} | Payment
{% endblock title %}


{% block sidebar_items %}

<!-- Heading -->
<div class="sidebar-heading">
    Board
</div>

<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
        aria-controls="collapseTwo">
        <i class="fas fa-fw fa-university"></i>
        <span>Admission</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Cousrses</h6>
            <a class="collapse-item" href="{% url 'dashboard:courses_data' 1 %}">quran with tajweed</a>
            <a class="collapse-item" href="{% url 'dashboard:courses_data' 2 %}">islam for kids</a>
            <a class="collapse-item" href="{% url 'dashboard:courses_data' 3 %}">noorani qauida</a>
        </div>
    </div>
</li>

<!-- Nav Item - Utilities Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true"
        aria-controls="collapseUtilities">
        <i class="fas fa-fw fa-tag"></i>
        <span>Take Trial</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Courses</h6>
            <a class="collapse-item" href="">quran with tajweed</a>
            <a class="collapse-item" href="">islam for kids</a>
            <a class="collapse-item" href="">noorani qauida</a>
        </div>
    </div>
</li>

<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
    Addons
</div>

<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false"
        aria-controls="collapsePages">
        <i class="fas fa-fw fa-folder"></i>
        <span>Quick Links</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Links</h6>
            <a class="collapse-item" href="{% url 'main:index' %}">Home</a>
            <a class="collapse-item" href="{% url 'main:about' %}">About</a>
            <a class="collapse-item" href="{% url 'dashboard:courses' %}">Courses</a>
            <a class="collapse-item" href="{% url 'main:contact' %}">Contact</a>
        </div>
    </div>
</li>

<!-- Nav Item - Change Password -->
<li class="nav-item">
    <a class="nav-link" href="{% url 'my_account' %}">
        <i class="fas fa-fw fa-user"></i>
        <span>Profile</span></a>
</li>

<!-- Nav Item - Logout -->
<li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">
        <i class="fas fa-sign-out-alt fa-sm fa-fw"></i>
        <span>Logout</span></a>
</li>

<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>

</ul>
{% endblock sidebar_items %}

{% block page_content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                        <img src="{% static 'images/jazzcash-logo.png' %}" width="100%" height="100%" alt="">
                    </div>
                    <div class="col-12 col-md-6 col-lg-8 col-xl-9 p-4">
                        <h2 class="h2 text-danger mb-2 font-weight-bold text-primary">Pay With Jazzcash</h2>
                        <h6 class="h6">JazzCash HTTP POST Confirmation (Page Redirection) Testing</h6>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="jsformWrapper">
                        <form name="jsform" method="post"
                            action="{% url 'payments:payment_confirm' 43 request.user.id %}">

                            <!-- Merchent Details - Info -->
                            <div class="form-group">
                                <label for="pp_MerchantID">pp_MerchantID: </label>
                                <input class="form-control" type="text" name="pp_MerchantID" id="pp_MerchantID"
                                    value="M12345">
                            </div>

                            <!-- Tansaction ID -->
                            <div class="form-group">
                                <label for="pp_TxnRefNo">pp_TxnRefNo: </label>
                                <input class="form-control" type="text" name="pp_TxnRefNo" id="pp_TxnRefNo"
                                    value="T12345">
                            </div>

                            <!-- Amount To Pay -->
                            <div class="form-group">
                                <label for="pp_Amount">pp_Amount: </label>
                                <input class="form-control" type="text" name="pp_Amount" id="pp_Amount" value="100000">
                            </div>

                            <!-- Transaction Retreival Reference -->
                            <div class="form-group">
                                <label for="pp_RetreivalReferenceNo">pp_RetreivalReferenceNo: </label>
                                <input class="form-control" type="text" name="pp_RetreivalReferenceNo"
                                    id="pp_RetreivalReferenceNo" value="RT12345">
                            </div>

                            <!-- Secure Hash Value -->
                            <div class="form-group">
                                <label for="pp_SecureHash">pp_SecureHash: </label>
                                <input class="form-control" type="text" name="pp_SecureHash" id="pp_SecureHash"
                                    value="HMACsha256-12345">
                            </div>

                            <!-- Extras -->
                            <div class="form-group">
                                <label for="pp_ResponseCode">pp_ResponseCode: </label>
                                <input class="form-control" type="text" name="pp_ResponseCode" id="pp_ResponseCode"
                                    value="000">
                            </div>

                            <div class="form-group">
                                <label for="pp_ResponseMessage">pp_ResponseMessage: </label>
                                <input class="form-control" type="text" id="pp_ResponseMessage"
                                    name="pp_ResponseMessage" value="">
                            </div>

                            <button type="button" class="btn btn-block btn-success"
                                onclick="submitForm()">Submit</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock page_content %}


{% block script %}
<script>
    function submitForm() {
        document.jsform.submit();
    }
</script>

{% endblock script %}