dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"
urlpatterns = [
    path("<int:user_id>/", views.dashboard, name="dashboard"),
    path(
        "courses/",
        views.courses,
        name="courses",
    ),
    path("courses/<int:course_id>/", views.courses_data, name="courses_data"),
    path("take_trial/", views.take_trial, name="take_trial"),
    path("trial_confirm/<int:course_id>", views.confirm_trial, name="trial_confirm"),
    path("contact/", views.contact, name="contact"),
]

main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("courses/<int:course_id>", views.courses, name="courses"),
    path(
        "course/quran_with_tajweed/<int:course_id>",
        views.quran_with_tajweed,
        name="quran_with_tajweed",
    ),
    path(
        "course/islam_for_kids/<int:course_id>",
        views.islam_for_kids,
        name="islam_for_kids",
    ),
    path(
        "course/noorani_qauida/<int:course_id>",
        views.noorani_qauida,
        name="noorani_qauida",
    ),
    path("contact/", views.contact, name="contact"),
    path("test_error_404/", views.test_error_404, name="error_404"),
    path("test_error_403/", views.test_error_403, name="error_403"),
    path("test_error_400/", views.test_error_400, name="error_400"),
    path("test_error_500/", views.test_error_500, name="error_500"),
]

online_learning_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # APPLICATIONS URLS CONFIG. REF.
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/admin/", include("admin_dashboard.urls")),
    path("payments/", include("payments.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# error hanlders
handler404 = "main.views.error_404"
handler500 = "main.views.error_500"
handler403 = "main.views.error_403"
handler400 = "main.views.error_400"

templates/base.html
<!doctype html>
<html lang="en">

{% load static %}

<head>
  <title>
    {% block title %}
    Al-Siraj
    {% endblock title %}
  </title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- SEO meta tags -->

  {% block meta-tags %}

  {% endblock meta-tags %}

  <!-- Bootstrap CSS as well as custom css-->
  <link rel="stylesheet" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'scss/style.css' %}">

  {% block stylesheet %} {% endblock stylesheet %}
</head>

<body>

  {% block body %}

  <!-- navbar start -->
  <nav class="navbar navbar-expand-lg py-2 navbar-dark bg-primary">
    <div class="container">
      <!-- navbar logo -->
      <a class="navbar-brand ml-3" href="{% url 'main:index' %}">AL-Siraj</a>
      <!-- hamburger menu icon -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% block navbar-items %}
        <!-- navbar items -->
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0 align-items-lg-center">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item"><a class="nav-link" href="{% url 'main:about' %}">About</a></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#!" id="dropdownId" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">Courses</a>
            <div class="dropdown-menu" aria-labelledby="dropdownId">
              <a class="dropdown-item" href="{% url 'main:quran_with_tajweed' 1 %}">Quran With Tajweed</a>
              <a class="dropdown-item" href="{% url 'main:islam_for_kids' 2 %}">Isalm For Kids</a>
              <a class="dropdown-item" href="{% url 'main:noorani_qauida' 3 %}">Noorani Qaida</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="!#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">Fee Chart</a>
            <div class="dropdown-menu" aria-labelledby="dropdownId">
              <a class="dropdown-item" href="{% url 'main:courses' 1 %}">Quran With Tajweed</a>
              <a class="dropdown-item" href="{% url 'main:courses' 2 %}">Isalm For Kids</a>
              <a class="dropdown-item" href="{% url 'main:courses' 3 %}">Noorani Qaida</a>
            </div>
          </li>
          <li class="nav-item"><a class="nav-link" href="{% url 'main:contact' %}">Contact</a></li>

          {% if user.is_authenticated %}
          <!-- Nav Item - User Information -->
          <li class="nav-item dropdown no-arrow ml-0 ml-lg-4">
            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#!" id="userDropdown" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img class="img-profile rounded-circle" style="width: 30px; height: 30px;"
                src="{{ request.user.student.profile_image.url }}">
              <span class="ml-2 mr-1 text-gray-600 small" style="font-size: 18px;">{{request.user.username}}</span>
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="{% url 'dashboard:dashboard' request.user.id %}">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Dashboard
              </a>
              <a class="dropdown-item" href="{% url 'my_account' %}">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
              </a>
              <a class="dropdown-item" href="{% url 'password_change' %}">
                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                Change Password
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
              </a>
            </div>
          </li>
          {% else %}
          <li class="nav-item ml-0 ml-lg-4">
            <a href="{% url 'login' %}" class="btn btn-secondary">Login</a>
            <a href="{% url 'sign_up' %}" class="btn btn-outline-secondary">Register</a>
          </li>
          {% endif %}

        </ul>
        <!-- navbar items end -->
        {% endblock navbar-items %}
        <!-- navbar form buttons -->
        <div class="my-lg-0 ml-0 ml-lg-5">

        </div>
      </div>
    </div>
  </nav>

  <!-- header start -->
  <header class="bg-primary">
    <div class="container">
      <!-- outer row -->
      <div class="row justify-content-center">
        <!-- hero heading -->
        <div class="col-12 col-sm-12 col-md-10 col-lg-7  py-5 px-4">
          {% block header %}
          header
          {% endblock header %}
        </div>
      </div>
    </div>
  </header>
  <!-- header end -->

  {% block main %}

  {% endblock main %}


  {% block footer %}
  <!-- footer start -->
  <footer class="bg-primary">
    <div class="container py-4">
      <div class="row justify-content-center">
        <div class="col-12 col-sm-12 col-lg-10 text-center">
          <h3 class="h3">Quick <span class="color">Links</span></h3>
          <nav class="nav mt-2 justify-content-center">
            <a class="nav-link active" href="{% url 'dashboard:courses' %}">Get Admission</a>
            <a class="nav-link" href="{% url 'dashboard:take_trial' %}">Start Free Trial</a>
            <a class="nav-link" href="{% url 'main:courses' 1 %}">Pricings</a>
            <a class="nav-link" href="{% url 'main:courses' 1 %}">Courses</a>
            <a class="nav-link" href="{% url 'main:contact' %}">Contact Us</a>
          </nav>
        </div>
        <div class="col-12 col-sm-12 col-lg-10 text-center mt-3">
          <h3 class="h3">Developed By:</h3>
          <!-- Button trigger modal -->
          <a class='btn btn-secondary mt-3 mt-sm-0' data-toggle="modal" data-target="#userModel">
            &#8594; Muhammad Amir Abbasi
          </a>
          <a class='btn btn-secondary mt-3 mt-sm-0' data-toggle="modal" data-target="#userModel">
            &#8594; Hussain Ahmad Khan
          </a>
          <!-- Modal -->
          <div class="modal fade m-0" id="userModel" tabindex="-1" role="dialog" aria-labelledby="UserModelLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content text-dark">
                <div class="modal-header">
                  <h5 class="modal-title" id="UserModelLabel">Developers</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="row">
                    <div class="col-3 profile-image">
                      <img src="{% static 'images/undraw_profile_2.svg' %}" width="100%" height="100%" alt="">
                    </div>
                    <div class="col-9 text-left profile-card">
                      <h5 class="h5">Muhammad Amir Abbasi</h5>
                      <p class="small">Full Stack Developer</p>
                      <!-- Social buttons -->
                      <ul class="list-unstyled list-inline icon-list">
                        <li class="list-inline-item">
                          <a href="https://www.facebook.com/daniyal.abbasi.1610/"
                            class="btn-floating btn btn-circle btn-sm btn-primary text-white">
                            <i class="fab fa-facebook-f"> </i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a href="https://twitter.com/Daniyal60990408"
                            class="btn-floating btn btn-circle btn-sm btn-secondary text-white">
                            <i class="fab fa-twitter"> </i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a href="mailto:muhammadamir5670@gmail.com"
                            class="btn-floating btn btn-circle btn-sm btn-danger text-white">
                            <i class="fab fa-google"> </i>
                          </a>
                        </li>
                      </ul>
                      <!-- Social buttons -->
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-3 profile-image">
                      <img src="{% static 'images/undraw_profile_2.svg' %}" width="100%" height="100%" alt="">
                    </div>
                    <div class="col-9 text-left profile-card">
                      <h5 class="h5">Hussain Ahmad Khan</h5>
                      <p class="small">Front End Developer</p>
                      <!-- Social buttons -->
                      <ul class="list-unstyled list-inline icon-list">
                        <li class="list-inline-item">
                          <a href="https://www.facebook.com/hussaunkhan.khan"
                            class="btn-floating btn btn-circle btn-sm btn-primary text-white">
                            <i class="fab fa-facebook-f"> </i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="btn-floating btn btn-circle btn-sm btn-secondary text-white">
                            <i class="fab fa-twitter"> </i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="btn-floating btn btn-circle btn-sm btn-danger text-white">
                            <i class="fab fa-google"> </i>
                          </a>
                        </li>
                      </ul>
                      <!-- Social buttons -->
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Copyright -->
    <div class="footer-copyright text-center bg-secondary py-3">© 2020 Copyright:
      <a href="#!" class="text-white ml-1"> Al-Siraj Online Quran Learning Academy</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- footer end -->
  {% endblock footer %}

  {% endblock body %}





  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

  <!-- Optional JavaScript -->
  {% block script %}
  {% endblock script %}

</body>

</html>

templates/d_base.html
<!doctype html>
<html lang="en">

{% load static %}

<head>
    <title>
        {% block title %}
        web-Application
        {% endblock title %}
    </title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'scss/style.css' %}">

    <!-- Custom CSS -->
    {% block stylesheet %} {% endblock stylesheet %}

</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center"
                href="{% url 'dashboard:dashboard' request.user.id %}">
                {% block dashboard_title %}
                <div class="sidebar-brand-text mx-3">Student panel</div>
                {% endblock dashboard_title %}
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard:dashboard' request.user.id %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            {% block sidebar_items %}

            <!-- Heading -->
            <div class="sidebar-heading">
                Board
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-university"></i>
                    <span>Admission</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Cousrses</h6>
                        <a class="collapse-item" href="{% url 'dashboard:courses_data' 1 %}">quran with tajweed</a>
                        <a class="collapse-item" href="{% url 'dashboard:courses_data' 2 %}">islam for kids</a>
                        <a class="collapse-item" href="{% url 'dashboard:courses_data' 3 %}">noorani qauida</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-tag"></i>
                    <span>Take Trial</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Courses</h6>
                        <a class="collapse-item" href="{% url 'dashboard:take_trial' %}">quran with tajweed</a>
                        <a class="collapse-item" href="{% url 'dashboard:take_trial' %}">islam for kids</a>
                        <a class="collapse-item" href="{% url 'dashboard:take_trial' %}">noorani qauida</a>
                    </div>
                </div>
            </li>
            <!-- Nav Item - Logout -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard:contact' %}">
                    <i class="fas fa-envelope fa-fw"></i>
                    <span>contact</span></a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                    aria-expanded="false" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Quick Links</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Links</h6>
                        <a class="collapse-item" href="{% url 'main:index' %}">Home</a>
                        <a class="collapse-item" href="{% url 'main:about' %}">About</a>
                        <a class="collapse-item" href="{% url 'dashboard:courses' %}">Courses</a>
                        <a class="collapse-item" href="{% url 'main:contact' %}">Contact</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Courses"
                    aria-expanded="false" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Courses</span>
                </a>
                <div id="Courses" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Courses</h6>
                        <a class="collapse-item" href="{% url 'main:quran_with_tajweed' 1 %}">Quran With Tajweed</a>
                        <a class="collapse-item" href="{% url 'main:islam_for_kids' 2 %}">Islam For Kids</a>
                        <a class="collapse-item" href="{% url 'main:noorani_qauida' 3 %}">Noorani Qauida</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Change Password -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my_account' %}">
                    <i class="fas fa-fw fa-user"></i>
                    <span>Profile</span></a>
            </li>

            <!-- Nav Item - Logout -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw"></i>
                    <span>Logout</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        {% endblock sidebar_items %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->

            {% block main %}
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">


                        {% block topbar_items %}

                        {% endblock topbar_items %}

                        <div class="topbar-divider d-none d-sm-block"></div>
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span
                                    class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.username}}</span>
                                <img class="img-profile rounded-circle"
                                    src="{{request.user.student.profile_image.url}}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{% url 'dashboard:dashboard' user.id %}">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Dashboard
                                </a>
                                <a class="dropdown-item" href="{% url 'my_account' %}">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="{% url 'password_change' %}">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Change Password
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid text-dark">

                    {% block page_content %}

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

                    {% endblock page_content %}

                </div>
                <!-- /.container-fluid -->

            </div>
            {% endblock main %}
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-gray-300 text-dark">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Al-siraj 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <!-- Optional JavaScript -->
    <script src="{% static 'js/dashboard.js' %}"></script>

    {% block script %}

    {% endblock script %}


</body>

</html>