dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"
urlpatterns = [
    path("<int:user_id>/", views.dashboard, name="dashboard"),
    path(
        "courses/",
        views.courses,
        name="courses",
    ),
    path("courses/<int:course_id>/", views.courses_data, name="courses_data"),
    path("take_trial/", views.take_trial, name="take_trial"),
    path("trial_confirm/<int:course_id>", views.confirm_trial, name="trial_confirm"),
    path("contact/", views.contact, name="contact"),
]

main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("courses/<int:course_id>", views.courses, name="courses"),
    path(
        "course/quran_with_tajweed/<int:course_id>",
        views.quran_with_tajweed,
        name="quran_with_tajweed",
    ),
    path(
        "course/islam_for_kids/<int:course_id>",
        views.islam_for_kids,
        name="islam_for_kids",
    ),
    path(
        "course/noorani_qauida/<int:course_id>",
        views.noorani_qauida,
        name="noorani_qauida",
    ),
    path("contact/", views.contact, name="contact"),
    path("test_error_404/", views.test_error_404, name="error_404"),
    path("test_error_403/", views.test_error_403, name="error_403"),
    path("test_error_400/", views.test_error_400, name="error_400"),
    path("test_error_500/", views.test_error_500, name="error_500"),
]

online_learning_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # APPLICATIONS URLS CONFIG. REF.
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/admin/", include("admin_dashboard.urls")),
    path("payments/", include("payments.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# error hanlders
handler404 = "main.views.error_404"
handler500 = "main.views.error_500"
handler403 = "main.views.error_403"
handler400 = "main.views.error_400"

payments/urls.py
from django.urls import path

from . import views

app_name = "payments"
urlpatterns = [
    path("checkout/<int:course_id>", views.checkout, name="checkout"),
    path(
        "checkout/<int:course_id>/redirect/<str:T_method>/",
        views.checkout_redirect,
        name="checkout_redirect",
    ),
    path(
        "api/test_checkout/<int:course_id>",
        views.test_checkout,
        name="checkout_testing",
    ),
    path(
        "api/test_checkout/confirmation",
        views.test_checkout_confirmation,
        name="checkout_testing",
    ),
    path(
        "payment_confirm/<int:course_id>/<int:user_id>",
        views.payment_confirm,
        name="payment_confirm",
    ),
    path(
        "payment/status/<int:enrollment_id>/<int:transaction_id>",
        views.payment_status,
        name="payment_status",
    ),
    path(
        "payment/message/",
        views.payment_message,
        name="payment_message",
    ),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.shortcuts import Http404, get_object_or_404


from datetime import timedelta


# Create your models here.


class Currency(models.Model):
    currencies = [
        ("$", "Dollors"),
        ("€", "Euros"),
        ("£", "Pounds"),
    ]

    currency_name = models.CharField(
        max_length=1,
        choices=currencies,
        default="$",
    )
    currency_value = models.IntegerField(null=False, blank=False, default=100)

    def __str__(self):
        return self.currency_name


class Course(models.Model):
    counteries = [
        ("US", "United States / America"),
        ("EU", "Europe"),
        ("UK", "United Kingdom"),
        ("CA", "Canada"),
        ("OT", "Other"),
    ]

    course_name = models.CharField(max_length=70)
    classes_per_week = models.IntegerField(default=2)
    class_duration = models.IntegerField(default=30)
    country = models.CharField(
        max_length=2,
        choices=counteries,
        default="OT",
    )
    pricing = models.IntegerField(default=0)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, null=True)
    user = models.ManyToManyField(
        User,
        through="Enrollment",
        through_fields=("course", "user"),
        editable=False,
    )

    def classes_per_month(self):
        """
        method for calculating classes per month
        """
        return self.classes_per_week * 4

    def get_course(self, course_id):
        """
        getting courses
        """
        if course_id == 1:
            return (
                self.objects.filter(course_name="quran with tajweed"),
                "quran with tajweed",
            )
        elif course_id == 2:
            return (self.objects.filter(course_name="islam for kids"), "islam for kids")
        elif course_id == 3:
            return (self.objects.filter(course_name="noorani qauida"), "noorani qauida")
        else:
            raise Http404("Invalid Request, Course not Found......")

    def seperate_query_sets(self, query_set):
        _US = query_set.filter(country="US")
        _UK = query_set.filter(country="UK")
        _CA = query_set.filter(country="CA")
        _EU = query_set.filter(country="EU")
        return {"US": _US, "UK": _UK, "CA": _CA, "EU": _EU}

    def to_PKR(self):
        return self.currency.currency_value * self.pricing

    def __str__(self):
        return "{} | {}".format(self.course_name, self.country)


class Student(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, editable=False, related_name="student"
    )
    profile_image = models.ImageField(null=True, blank=True, default="person-icon.png")
    email_confirmed = models.BooleanField(default=False)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        print("Created Student")
        if created:
            Student.objects.create(user=instance)
        instance.student.save()

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.student.save()

    def get_students(self, _type=None):
        if not _type:
            return User.objects.filter(groups__name="students")
        else:
            return User.objects.filter(groups__name=_type)

    def __str__(self):
        return self.user.username


class Trial(models.Model):
    status = models.BooleanField(default=True)
    started_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(auto_now_add=True)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, related_name="trial"
    )
    course = models.CharField(max_length=150, null=True)

    def trial_available(self):
        return self.status

    def set_trial_datetime(self):
        now = timezone.now()
        period = timedelta(days=3)
        self.started_date = now
        self.end_date = now + period

    def get_active_trialies(self):
        now = timezone.now()
        return self.objects.filter(end_date__gt=now).exclude(user__groups__id=4)

    def get_inactive_trialies(self):
        now = timezone.now()
        return self.objects.filter(end_date__lt=now).exclude(user__groups__id=4)

    def deactive_trialies(self):
        now = timezone.now()
        trialies = self.get_inactive_trialies(self)
        for trialy in trialies:
            trialy.completed = True

    def get_trials(self):
        return self.objects.all().exclude(user__groups__id=4)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        print("Created Trial")
        if created:
            Trial.objects.create(user=instance)
        instance.trial.save()

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.student.save()

    def trial_status(self):
        return self.end_date > timezone.now()


class Enrollment(models.Model):
    def set_expiery():
        period = timedelta(days=30)
        return timezone.now() + period

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    expiries_at = models.DateTimeField(default=set_expiery)

    def user_enrollments(self, user_id):
        return self.objects.filter(user__id=user_id)

    def get_enrollment(self, user_id, enrollment_id):
        enrollment = self.objects.filter(id=enrollment_id, user__id=user_id)
        if enrollment:
            return enrollment[0]
        else:
            raise Http404("Page Not found")

    def get_enrollments(self):
        return self.objects.all()

    def active_enrollments(self):
        now = timezone.now()
        return self.objects.filter(expiries_at__gt=now)

    def inactive_enrollments(self):
        now = timezone.now()
        return self.objects.filter(expiries_at__lt=now)

    def deactivate_enrollments(self):
        now = timezone.now()
        trialies = self.inactive_enrollments(self)
        for trialy in trialies:
            trialy.completed = True

    def enrollment_status(self):
        return self.expiries_at > timezone.now()


def add_user_to_group(group_id, user_id):
    user = get_object_or_404(User, pk=user_id)
    group = get_object_or_404(Group, pk=group_id)
    group.user_set.add(user)


def remove_user_from_group(group_id, user_id):
    user = get_object_or_404(User, pk=user_id)
    group = get_object_or_404(Group, pk=group_id)
    user.groups.remove(group)


def get_data_for_admin():
    students = {
        "students": Student.get_students(Student).count(),
        "enrolled": Student.get_students(Student, _type="enroll_students").count(),
        "on_trial": Student.get_students(Student, _type="students_on_trial").count(),
    }
    enrollments = {
        "all": Enrollment.get_enrollments(Enrollment).count(),
        "active": Enrollment.active_enrollments(Enrollment).count(),
        "inactive": Enrollment.inactive_enrollments(Enrollment).count(),
    }
    return {
        "students": students,
        "enrollments": enrollments,
    }


def get_students(_type=None):
    if not _type:
        return Enrollment.objects.all().exculde(user__groups__id=4)
    elif _type == "students_on_trial":
        return Student.get_students(Student, _type="students_on_trial")
    elif _type == "active":
        return Enrollment.active_enrollments(Enrollment)
    elif _type == "inactive":
        return Enrollment.inactive_enrollments(Enrollment)
    else:
        raise Http404("Page Not Found")


def get_user_enrollment_count():
    users = User.objects.all().exclude(groups__id=4)
    counts = []
    for user in users:
        counts.append(Enrollment.user_enrollments(Enrollment, user.id).count())
    return counts

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib import messages
from online_learning_system.settings import EMAIL_HOST_USER

from .models import Course

# Create your views here.


def index(request):
    return render(request, "main/index.html", context={})


def about(request):
    return render(request, "main/about.html", context={})


def courses(request):
    return render(request, "main/courses.html", context={})


def quran_with_tajweed(request, course_id):
    if course_id != 1:
        print("error occurred")
        raise Http404("Page Not Found")
    context = {}
    return render(request, "main/quran_with_tajweed.html", context=context)


def islam_for_kids(request, course_id):
    if course_id != 2:
        raise Http404("Page Not Found")
    context = {}
    return render(request, "main/islam_for_kids.html", context=context)


def noorani_qauida(request, course_id):
    if course_id != 3:
        raise Http404("Page Not Found")
    context = {}
    return render(request, "main/noorani_qauida.html", context=context)


def contact(request):
    if request.method == "POST":
        f_name = request.POST["f_name"]
        l_name = request.POST["l_name"]
        user_email = request.POST["user_email"]
        user_message = request.POST["user_message"]
        print("Post Method Occurred")
        message = render_to_string(
            "main/contact_email.html",
            {
                "f_name": f_name,
                "l_name": l_name,
                "email": user_email,
                "message": user_message,
            },
        )
        status = send_mail(
            "A-Siraj Help Center",
            message,
            from_email=EMAIL_HOST_USER,
            recipient_list=["nabeelrana892@gmail.com"],
        )
        if status != 0:
            messages.info("Your Message Has been successfully sent to the Admin")
        else:
            messages.info("Unable to send message")
        return redirect("main:contact")

    else:
        id = request.GET.get("id")
        if id:
            course = get_object_or_404(Course, pk=id)
            context = {"course": course}
        else:
            context = {}
        return render(request, "main/contact.html", context=context)


def courses(request, course_id):
    courses, name = Course.get_course(Course, course_id)
    if not courses:
        raise Http404("invalid request")
    else:
        courses = Course.seperate_query_sets(Course, courses)
        context = {"name": name, "courses": courses}
        return render(request, "main/courses.html", context=context)


# TESTING ERROR ERROR VIEWS
def test_error_404(request):
    context = {}
    return render(request, "main/404.html", context)


def test_error_403(request):
    context = {}
    return render(request, "main/403.html", context)


def test_error_400(request):
    context = {}
    return render(request, "main/400.html", context)


def test_error_500(request):
    context = {}
    return render(request, "main/500.html", context)


# ERROR VIEWS
def error_404(request, exception):
    context = {}
    return render(request, "main/404.html", context)


def error_403(request, exception):
    context = {}
    return render(request, "main/403.html", context)


def error_400(request, exception):
    context = {}
    return render(request, "main/400.html", context)


def error_500(request):
    context = {}
    return render(request, "main/500.html", context)

main/templates/main/contact.html
{% extends 'base.html' %}


{% block title %}
Contact Us
{% endblock title %}


{% block navbar-items %}
<!-- navbar items -->
<ul class="navbar-nav ml-auto mt-2 mt-lg-0 align-items-lg-center">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'main:index' %}">Home</a>
    </li>
    <li class="nav-item"><a class="nav-link" href="{% url 'main:about' %}">About</a></li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#!" id="dropdownId" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">Courses</a>
        <div class="dropdown-menu" aria-labelledby="dropdownId">
            <a class="dropdown-item" href="{% url 'main:quran_with_tajweed' 1 %}">Quran With Tajweed</a>
            <a class="dropdown-item" href="{% url 'main:islam_for_kids' 2 %}">Isalm For Kids</a>
            <a class="dropdown-item" href="{% url 'main:noorani_qauida' 3 %}">Noorani Qaida</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="!#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">Fee Chart</a>
        <div class="dropdown-menu" aria-labelledby="dropdownId">
            <a class="dropdown-item" href="{% url 'main:courses' 1 %}">Quran With Tajweed</a>
            <a class="dropdown-item" href="{% url 'main:courses' 2 %}">Isalm For Kids</a>
            <a class="dropdown-item" href="{% url 'main:courses' 3 %}">Noorani Qaida</a>
        </div>
    </li>
    <li class="nav-item active"><a class="nav-link" href="{% url 'main:contact' %}">Contact <span
                class="sr-only">(current)</span></a></li>

    {% if user.is_authenticated %}
    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow ml-0 ml-lg-4">
        <a class="nav-link dropdown-toggle d-flex align-items-center" href="#!" id="userDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="img-profile rounded-circle" style="width: 30px; height: 30px;"
                src="{{ request.user.student.profile_image.url }}">
            <span class="ml-2 mr-1 text-gray-600 small" style="font-size: 18px;">{{request.user.username}}</span>
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="{% url 'dashboard:dashboard' request.user.id %}">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Dashboard
            </a>
            <a class="dropdown-item" href="{% url 'my_account' %}">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                Change Profile Image
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
            </a>
        </div>
    </li>
    {% else %}
    <li class="nav-item ml-0 ml-lg-4">
        <a href="{% url 'login' %}" class="btn btn-secondary">Login</a>
        <a href="{% url 'sign_up' %}" class="btn btn-outline-secondary">Register</a>
    </li>
    {% endif %}

</ul>
<!-- navbar items end -->
{% endblock navbar-items %}


{% block header %}
<h1 class="h1 display-4">Contact <span class="text-secondary">Us</span></h1>
{% endblock header %}


{% block main %}


{% if course %}
<div class="container text-dark text-center">
    <div class="my-4">
        <a href="{% url 'payments:checkout' course.id %}" class="btn btn-lg btn-secondary mb-4">Pay Online</a>
        <h2 class="text-center h2">OR</h2>
    </div>
</div>
{% endif %}

<!-- section - 1 - Contact Info -->
<h2 class="text-center text-dark my-4">Contact <span class="text-secondary">Us!</span></h2>

<section class="text-dark">
    <div class="container">
        <!-- displaying the non form field errors -->
        {% for message in messages %}
        <div class="alert alert-info" role="alert">
            <strong>Info!</strong>
            <p {% if forloop.last %} class="mb=0" {% endif %}>{{ message }}</p>
        </div>
        {% endfor %}

        <div class="row">
            <!-- Skype Info  -->
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card border-left-secondary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-secondary text-uppercase mb-1">
                                    Skype ID</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">Hafiz Muhammad Nabeel Ali</div>
                            </div>
                            <div class="col-auto">
                                <div class="icon text-center"><i
                                        style="border-color:#007bff;border-width:1px;background-color:#007bff;box-sizing:content-box;height:50px;width:50px;line-height:50px;border-radius:50%;color:#ffffff;font-size:30px;"
                                        class="fontawesome-icon fa-skype fab circle-yes"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Skype Info  -->
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                    Whats App Number</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">+92 3104608450</div>
                            </div>
                            <div class="col-auto">
                                <div class="icon text-center"><i
                                        style="border-color:#28a745;border-width:1px;background-color:#28a745;box-sizing:content-box;height:50px;width:50px;line-height:50px;border-radius:50%;color:#ffffff;font-size:30px;"
                                        class="fontawesome-icon fa-whatsapp fab circle-yes"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Skype Info  -->
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-secondary text-uppercase mb-1">
                                    Mailing</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">al.siraj5670@gmail.com</div>
                            </div>
                            <div class="col-auto">
                                <div class="icon text-center"><i
                                        style="border-color:#de5246;border-width:1px;background-color:#de5246;box-sizing:content-box;height:50px;width:50px;line-height:50px;border-radius:50%;color:#ffffff;font-size:30px;"
                                        class="fontawesome-icon fa-envelope-open-text fas circle-yes"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row my-5">
            <div class="col-12 col-sm-12 col-lg-6">
                <h4 class="h4"><i class="fa fa-map-marker text-danger mr-3"></i><b>Location</b></h3>
                    <iframe
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3398.67802362246!2d74.36937331515226!3d31.58787618134732!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzHCsDM1JzE2LjQiTiA3NMKwMjInMTcuNiJF!5e0!3m2!1sen!2s!4v1607855172821!5m2!1sen!2s"
                        width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen=""
                        aria-hidden="false" tabindex="0"></iframe>
            </div>
            <div class="col-12 col-sm-12 col-lg-6">
                <form class="bg-white form-in-col text-dark" method="POST" action="{% url 'main:contact' %}">
                    <h4 class="h4"><b>Get <span class="text-secondary">In Touch</span></b></h4>
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputFName">First Name</label>
                            <input type="text" required name="f_name" class="form-control" id="inputFName"
                                placeholder="Nabeel">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputLName">Last Name</label>
                            <input type="text" required name="l_name" class="form-control" id="inputLName"
                                placeholder="Chuadry">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail">Email</label>
                        <input type="email" required name="user_email" class="form-control" id="inputEmail"
                            placeholder="nabeelchuadry123@gmail.com">
                    </div>
                    <div class="form-group">
                        <label for="InputMessage">Message</label>
                        <textarea class="form-control" required name="user_message" id="InputMessage" rows="5"
                            placeholder="need some help, please ask we would love help you.........."></textarea>
                    </div>
                    <button type="submit" class="btn btn-secondary">Sign in</button>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- end of section - 1 - Contact Info -->
{% endblock main %}

main/templates/main/contact_email.html
{% autoescape off %}
Email From Alsiraj Help Center,
===================================================
User Information:
First Name: {{ f_name }}
First Name: {{ l_name }}
Email Address: {{ email }}
===================================================
Message:
{{message}}

===================================================
{% endautoescape %}